# Add your additional Hyprland configurations here

# ---- Autostart background apps ----
exec-once = sleep 3 && openrgb --profile "ArchGB"
exec-once = sleep 4 && linux-wallpaperengine-gui
exec-once = sleep 3 && /home/mau/Downloads/musicpresence-2.3.5-linux-x86_64.AppImage

# ---- Window rules to hide GUIs on startup ----
windowrule = workspace 3 silent, match:class ^org\.openrgb\.OpenRGB$
windowrule = workspace 3 silent, match:class ^linux-wallpaperengine-gui$

#windowrulev2 = nofocus, class:^org\.openrgb\.OpenRGB$
#windowrulev2 = nofocus, class:^linux-wallpaperengine-gui$

# ES-DE – always fullscreen
windowrule = match:class ^(es-de)$ fullscreen

